[tox]
requires = tox >= 4.25.0
env_list = ruff{posargs}, typing, doctest, clean, py31{0-3}{posargs}, combine

[testenv]
dependency_groups = test
runner = uv-venv-lock-runner
setenv =
   COVERAGE_FILE = .coverage.{py_dot_ver}
   COVERALLS_FLAG_NAME = {on_platform}_python{py_dot_ver}
   COVERALLS_PARALLEL = true
passenv =
   GITHUB_*
   COVERALLS_*

[testenv:ruff{,-ci}]
description = run ruff linter
dependency_groups = lint
commands =
   ruff: ruff check
   ruff-ci: ruff check --output-format=github
   ruff format --check
skip_install = true

[testenv:typing]
description = run mypy type checker
dependency_groups = typing, test
commands = mypy
skip_install = true

[testenv:clean]
description = clean up coverage files
commands = coverage erase

[testenv:doctest]
description = test code in Sphinx documentation
dependency_groups = doc, test
commands = sphinx-build -b doctest docs/source docs/build

[testenv:py31{0-3}{,-ci}]
description = run pytest on python {py_dot_ver}
depends = clean
dependency_groups =
   test
   py310-ci, py311-ci, py312-ci, py313-ci: ci
commands =
   pytest
   py310-ci, py311-ci, py312-ci, py313-ci: coveralls

[testenv:combine]
description = combine coverage files
depends = py3{10-13}{posargs}
setenv = COVERAGE_FILE = .coverage
commands = coverage combine
skip_install = true
