name: Publish to PyPI
on:
  workflow_dispatch:
  push:
    tags:
      - '+([0-9]).+([0-9]).+([0-9])?(@(a|b|rc)*([0-9]))'  # Matches PEP440 version tags

jobs:
  build:
    name: Build and upload release to PyPi
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/bpod-modules-ibl
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - run: uv build
      - run: uv publish
